<?php

namespace AeroGest\VolBundle\Repository;

/**
 * Paquet_ColisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Paquet_ColisRepository extends \Doctrine\ORM\EntityRepository
{
}
