<?php

namespace AeroGest\VolBundle\Repository;

/**
 * PaquetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaquetRepository extends \Doctrine\ORM\EntityRepository
{
}
