<?php

namespace AeroGest\VolBundle\Repository;

/**
 * Paquet_BagageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Paquet_BagageRepository extends \Doctrine\ORM\EntityRepository
{
}
