<?php

namespace AeroGest\VolBundle\Repository;

/**
 * Passager_ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Passager_ClientRepository extends \Doctrine\ORM\EntityRepository
{
}
