<?php

namespace AeroGest\VolBundle\Repository;

/**
 * Passager_PersonnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Passager_PersonnelRepository extends \Doctrine\ORM\EntityRepository
{
}
