<?php

namespace AeroGest\VolBundle\Repository;

/**
 * Site_EscaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Site_EscaleRepository extends \Doctrine\ORM\EntityRepository
{
}
