<?php

namespace AeroGest\VolBundle\Repository;

/**
 * Site_DestinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Site_DestinationRepository extends \Doctrine\ORM\EntityRepository
{
}
