<?php

namespace AeroGest\VolBundle\Repository;

/**
 * Tier_ExpediteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tier_ExpediteurRepository extends \Doctrine\ORM\EntityRepository
{
}
