aero_gest_vol_avion:
    resource: "@AeroGestVolBundle/Resources/config/routing/avion.yml"
    prefix:   /avion

aero_gest_vol_homepage:
    path:     /
    defaults: { _controller: AeroGestVolBundle:Default:index }

aero_gest_vol_compagnie:
        resource: "@AeroGestVolBundle/Resources/config/routing/compagnie.yml"
        prefix:   /compagnie

aero_gest_vol_bagages:
        resource: "@AeroGestVolBundle/Resources/config/routing/paquet_bagage.yml"
        prefix:   /bagages
aero_gest_vol_colis:
        resource: "@AeroGestVolBundle/Resources/config/routing/paquet_colis.yml"
        prefix:   /colis
aero_gest_vol_clients:
        resource: "@AeroGestVolBundle/Resources/config/routing/passager_client.yml"
        prefix:   /clients
aero_gest_vol_personnel:
        resource: "@AeroGestVolBundle/Resources/config/routing/passager_personnel.yml"
        prefix:   /personnel
aero_gest_vol_destinations:
        resource: "@AeroGestVolBundle/Resources/config/routing/site_destination.yml"
        prefix:   /destinations
aero_gest_vol_escales:
        resource: "@AeroGestVolBundle/Resources/config/routing/site_escale.yml"
        prefix:   /escales
aero_gest_vol_destinataires:
        resource: "@AeroGestVolBundle/Resources/config/routing/tier_destinataire.yml"
        prefix:   /destinataires
aero_gest_vol_expediteurs:
        resource: "@AeroGestVolBundle/Resources/config/routing/tier_expediteur.yml"
        prefix:   /expediteurs
aero_gest_vol_vol:
        resource: "@AeroGestVolBundle/Resources/config/routing/vol.yml"
        prefix:   /vol

